version: "3"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: always
    container_name: "api-gateway"
    hostname: "api-gateway"
    ports:
      - 8010:8010

  grpc-server:
    build:
      context: ./grpc-server
      dockerfile: Dockerfile
    restart: always
    container_name: "grpc-server"
    hostname: "grpc-server"
    ports:
      - 8011:8010
